apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pizza-backend
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/YOUR_USERNAME/pizza-party.git
    targetRevision: main
    path: manifests/backend   # <--- Pointing to backend code
  destination:
    server: https://kubernetes.default.svc
    namespace: intra-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
