apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pizza-party-parent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/unbeatable-abayomi/go_micro_services.git
    # ---------------------------------------------------------
    # THIS is where you target the branch for the PARENT APP
    targetRevision: feat/appOfapps   # Change this to 'infra-test' if you want!
    # ---------------------------------------------------------
    path: general_info/projects/Project_Portal/k8s/apps  # <--- Look at the "Card Catalog" folder
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # Parent apps usually live in the argocd namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true