# Shared ConfigMap for common configurations
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  AUTH_SERVICE_URL: "http://auth-service:8082"
  UPLOAD_SERVICE_URL: "http://upload-service:8083"

---
# jwt-secret-stringdata.yaml
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  JWT_SECRET: "your-secret-key"
---
# Persistent Volume for uploads
apiVersion: v1
kind: PersistentVolume
metadata:
  name: uploads-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/uploads
---
# Persistent Volume Claim for uploads
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi