apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  #namespace: agrocd-sync
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: false

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: upload-service-sa
  #namespace: agrocd-sync
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken : false

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  #namespace: agrocd-sync
  annotations:
    argocd.argoproj.io/sync-wave: "0"
automountServiceAccountToken: false
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  #namespace: agrocd-sync
  name: auth-pod-creator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "list",]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  #namespace: agrocd-sync
  name: upload-pod-creator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "list",]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  #namespace: agrocd-sync
  name: api-pod-creator
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "list",]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-create-pods-binding
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  #namespace: agrocd-sync
subjects:
- kind: ServiceAccount
  name: auth-service-sa
  # annotations:
  #   argocd.argoproj.io/sync-wave: "0"
  namespace: agrocd-sync
roleRef:
  kind: Role
  name: auth-pod-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: upload-create-pods-binding
  #namespace: agrocd-sync
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
- kind: ServiceAccount
  name: upload-service-sa
  namespace: agrocd-sync
  # annotations:
  #   argocd.argoproj.io/sync-wave: "0"
roleRef:
  kind: Role
  name: upload-pod-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-create-pods-binding
  #namespace: agrocd-sync
  annotations:
    argocd.argoproj.io/sync-wave: "0"
subjects:
- kind: ServiceAccount
  name: api-gateway-sa
  #namespace: agrocd-sync
  # annotations:
  #   argocd.argoproj.io/sync-wave: "0"
roleRef:
  kind: Role
  name: api-pod-creator
  apiGroup: rbac.authorization.k8s.io
  