apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: default
automountServiceAccountToken: false

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: upload-service-sa
  namespace: default
automountServiceAccountToken : false

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: default
automountServiceAccountToken: false
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: auth-pod-creator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "list",]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: upload-pod-creator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "list",]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: api-pod-creator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "list",]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-create-pods-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: auth-service-sa
  namespace: default
roleRef:
  kind: Role
  name: auth-pod-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: upload-create-pods-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: upload-service-sa
  namespace: default
roleRef:
  kind: Role
  name: upload-pod-creator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-create-pods-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: api-gateway-sa
  namespace: default
roleRef:
  kind: Role
  name: api-pod-creator
  apiGroup: rbac.authorization.k8s.io
  