apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service-sa
  namespace: default
automountServiceAccountToken: false

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: upload-service-sa
  namespace: default
automountServiceAccountToken : false

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway-sa
  namespace: default
automountServiceAccountToken: false
---