apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-application
spec:
  project: default
  source:
    repoURL: 'https://github.com/unbeatable-abayomi/go_micro_services.git'
    targetRevision: main
    path: ./my-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: yomi-namespace
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=true   
    

---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: postgresql
#   namespace: todo
#   annotations:
#     argocd.argoproj.io/sync-wave: "0"   

---

# apiVersion: v1
# kind: Namespace
# metadata:
#   name: todo
#   annotations:
#     argocd.argoproj.io/sync-wave: "0"   